/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#baeaff",
        "surface-container": "#edeeef",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#001f29",
        "inverse-surface": "#2e3132",
        "surface-variant": "#e1e3e4",
        "secondary-fixed": "#ffe088",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadb",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-background": "#191c1d",
        "background": "#f8f9fa",
        "error-container": "#ffdad6",
        "surface-tint": "#3a5f94",
        "outline-variant": "#c3c6d1",
        "secondary": "#735c00",
        "on-surface-variant": "#43474f",
        "on-surface": "#191c1d",
        "on-secondary-container": "#745c00",
        "primary": "#001e40",
        "surface": "#f8f9fa",
        "surface-container-high": "#e7e8e9",
        "secondary-container": "#fed65b",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed-variant": "#574500",
        "outline": "#737780",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#5da4c0",
        "on-primary-container": "#799dd6",
        "on-secondary-fixed": "#241a00",
        "inverse-primary": "#a7c8ff",
        "on-tertiary-fixed-variant": "#004d62",
        "tertiary-container": "#003848",
        "on-primary-fixed": "#001b3c",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#a7c8ff",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#00212c",
        "on-primary": "#ffffff",
        "primary-container": "#003366",
        "on-primary-fixed-variant": "#1f477b",
        "tertiary-fixed-dim": "#89d0ed",
        "inverse-on-surface": "#f0f1f2"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "stack-lg": "24px",
        "margin-desktop": "80px",
        "gutter": "32px",
        "stack-sm": "8px",
        "margin-mobile": "24px",
        "stack-md": "16px",
        "section-gap": "120px"
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-sm": ["Montserrat", "sans-serif"],
        "label-md": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.03em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
